# app/api/routes/chat.py
from fastapi import APIRouter, HTTPException, status, Header, Depends
from app.models.schemas import ChatRequest, ChatResponse, ErrorResponse
from app.services.model_router import ModelRouter
from app.core.config import get_settings
from app.core.auth import verify_api_key_with_provider_keys # Sử dụng phiên bản nâng cao
from typing import Dict, Any

router = APIRouter()
settings = get_settings()

@router.post(
    "/generate-text",
    response_model=ChatResponse,
    summary="Generate Text Response using the specified model",
    responses={
        status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {"model": ErrorResponse},
        status.HTTP_503_SERVICE_UNAVAILABLE: {"model": ErrorResponse},
    }
)
async def generate_chat_response(
    request_body: ChatRequest,
    x_google_api_key: str | None = Header(None, alias="X-Google-API-Key"),
    x_xai_api_key: str | None = Header(None, alias="X-xAI-API-Key"),
    x_gigachat_api_key: str | None = Header(None, alias="X-GigaChat-API-Key"),
    x_perplexity_api_key: str | None = Header(None, alias="X-Perplexity-API-Key"),
    auth_info: Dict[str, Any] = Depends(verify_api_key_with_provider_keys) # Sử dụng verify_api_key_with_provider_keys
):
    """
    Receives a user message and optional chat history, then returns
    a text response generated by the specified model via ModelRouter.
    """
    try:
        # Lấy provider keys từ DB (đã được giải mã)
        db_provider_keys = auth_info.get("provider_keys", {})
        
        # Chuẩn bị API keys dictionary với thứ tự ưu tiên:
        # 1. Từ header
        # 2. Từ DB (provider keys của người dùng)
        # 3. Từ settings (mặc định)
        provider_api_keys: Dict[str, str] = {}
        
        # Google key
        google_key = x_google_api_key or db_provider_keys.get("google") or settings.GOOGLE_AI_STUDIO_API_KEY
        
        # Grok key
        grok_key = x_xai_api_key or db_provider_keys.get("xai") or settings.XAI_API_KEY
        
        # GigaChat key
        gigachat_key = x_gigachat_api_key or db_provider_keys.get("gigachat") or settings.GIGACHAT_AUTH_KEY
        
        # Perplexity key
        perplexity_key = x_perplexity_api_key or db_provider_keys.get("perplexity") or settings.PERPLEXITY_API_KEY

        # Thêm key vào dictionary nếu có
        if google_key:
            provider_api_keys["google"] = google_key
        if grok_key:
            provider_api_keys["grok"] = grok_key
        if gigachat_key:
            provider_api_keys["gigachat"] = gigachat_key
        if perplexity_key:
            provider_api_keys["perplexity"] = perplexity_key

        # Use ModelRouter to route the request
        response_text, model_used = await ModelRouter.route_simple_chat(
            model=request_body.model,
            message=request_body.message,
            history=request_body.history,
            provider_api_keys=provider_api_keys
        )
        return ChatResponse(
            response_text=response_text,
            model_used=model_used
        )
    except HTTPException as http_exc:
        # Re-raise HTTPExceptions raised by the router/service
        raise http_exc
    except Exception as e:
        # Catch any other unexpected errors during chat generation
        # Log the error e here
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected error occurred during chat generation: {e}"
        )